"""
InviteLink model — Tracked Telegram invite links.

Stores metadata for every invite link the bot encounters or creates.
This is a core table for the invite tracking system — when a user
joins via a link, we match the ChatMemberUpdated.invite_link against
this table to resolve the inviter.

Each invite link has a unique URL (the Telegram invite link string)
and is associated with a group and a creator (the admin who generated it).

Telegram API fields mapped:
- invite_link → link_url
- name → name
- creator → creator_id
- expire_date → expire_date
- member_limit → member_limit
- creates_join_request → creates_join_request
- is_primary → is_primary
- is_revoked → is_revoked
- pending_join_request_count → pending_join_request_count
"""

from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from bot.database.base import Base, TimestampMixin, UUIDPrimaryKeyMixin


class InviteLink(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """
    Tracked Telegram group invite link.

    Stores both Telegram-provided metadata and bot-computed statistics.
    Links are never deleted — revoked links are kept for historical reference.
    """

    __tablename__ = "invite_links"

    # ==================== Foreign Keys ====================
    group_id: Mapped[int] = mapped_column(
        ForeignKey("groups.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc="The group this invite link belongs to.",
    )

    creator_id: Mapped[int] = mapped_column(
        ForeignKey("bot_users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc="Telegram user ID of the admin who created this link.",
    )

    # ==================== Link Data ====================
    link_url: Mapped[str] = mapped_column(
        String(512),
        nullable=False,
        unique=True,
        doc="The full invite link URL (e.g., 'https://t.me/+AbCdEfGhIjK').",
    )

    name: Mapped[str | None] = mapped_column(
        String(32),
        nullable=True,
        doc="Human-readable label for this link (max 32 chars per Telegram API).",
    )

    # ==================== Link Configuration ====================
    expire_date: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        doc="When this link expires (null = never expires).",
    )

    member_limit: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
        doc="Max number of users that can join via this link (null = unlimited).",
    )

    creates_join_request: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default=text("FALSE"),
        doc="If True, users must request to join and be approved by an admin.",
    )

    # ==================== Status Flags ====================
    is_primary: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default=text("FALSE"),
        doc="Whether this is the group's primary invite link.",
    )

    is_revoked: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default=text("FALSE"),
        doc="Whether this link has been revoked.",
    )

    is_bot_generated: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default=text("FALSE"),
        doc="Whether this link was generated by the bot (vs. manually by an admin).",
    )

    # ==================== Usage Statistics ====================
    # Telegram-reported usage count (from ChatInviteLink object)
    telegram_usage_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default=text("0"),
        doc="Usage count as reported by Telegram API.",
    )

    # Bot-tracked usage count (from our invite records)
    tracked_usage_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default=text("0"),
        doc="Usage count tracked by our bot (may differ from Telegram's count).",
    )

    # How many users who joined via this link are still in the group
    active_usage_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default=text("0"),
        doc="Number of users who joined via this link and are still members.",
    )

    pending_join_request_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default=text("0"),
        doc="Number of pending join requests via this link.",
    )

    # ==================== Timestamps ====================
    revoked_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        doc="When this link was revoked (null if still active).",
    )

    # ==================== Relationships ====================
    group: Mapped["Group"] = relationship(  # noqa: F821
        "Group",
        back_populates="invite_links",
    )

    creator: Mapped["BotUser"] = relationship(  # noqa: F821
        "BotUser",
        back_populates="created_invite_links",
    )

    invite_records: Mapped[list["InviteRecord"]] = relationship(  # noqa: F821
        "InviteRecord",
        back_populates="invite_link",
        lazy="noload",
    )

    # ==================== Indexes ====================
    __table_args__ = (
        # Fast lookup: "what links exist for this group?"
        Index("ix_invite_links_group", "group_id"),
        # Fast lookup: "what active links did this user create in this group?"
        Index(
            "ix_invite_links_creator_group",
            "creator_id",
            "group_id",
        ),
        # Fast lookup: non-revoked links only
        Index(
            "ix_invite_links_active",
            "group_id",
            "is_revoked",
            sqlite_where=text("is_revoked = FALSE"),
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<InviteLink(group={self.group_id}, "
            f"creator={self.creator_id}, "
            f"name={self.name!r}, "
            f"revoked={self.is_revoked})>"
        )

    @property
    def is_expired(self) -> bool:
        """Check if the invite link has expired."""
        if self.expire_date is None:
            return False
        from datetime import datetime, timezone

        return datetime.now(timezone.utc) > self.expire_date

    @property
    def is_usage_exhausted(self) -> bool:
        """Check if the invite link has reached its usage limit."""
        if self.member_limit is None:
            return False
        return self.tracked_usage_count >= self.member_limit

    @property
    def is_usable(self) -> bool:
        """Check if the invite link can still be used for new joins."""
        return (
            not self.is_revoked
            and not self.is_expired
            and not self.is_usage_exhausted
        )

    @property
    def retention_rate(self) -> float:
        """
        Calculate the retention rate for this link.

        Returns the percentage of users who joined via this link
        and are still members of the group.
        """
        if self.tracked_usage_count == 0:
            return 0.0
        return (self.active_usage_count / self.tracked_usage_count) * 100
